- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/connection/OceanBaseConnectionOptions.java
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/connection/OceanBaseConnectionPool.java
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/table/OceanBaseConnectorOptions.java
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/table/sink/OceanBaseDynamicTableSinkFactory.java
- pom.xml
Add startup option `driver-class`.
User should be able to specify the  JDBC driver.
No.
Yes, it's a required option.
Tested locally.
> add driver-class option

- flink-connector-oceanbase/pom.xml
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/connection/OceanBaseConnectionOptions.java
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/connection/OceanBaseConnectionPool.java
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/table/OceanBaseConnectorOptions.java
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/table/sink/OceanBaseDynamicTableSinkFactory.java
- pom.xml
Add option for connection pool.
The connector should not bind with specific connection pool.
No.
Yes, the `connection-pool` option is required.
Test locally.
> add option for connection pool

- README.md
- README_CN.md
Add README file.
Add more infos about usage.
No.
No.
Not needed.
> add README

- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/dialect/OceanBaseOracleDialect.java
Support upsert statement for OceanBase Oracle mode. Close #6 
To support oracle mode.
No.
No.
Tested locally.
> support upsert statement for ob oracle

- README.md
- README_CN.md
- tools/maven/shade/pom.xml
- tools/maven/shade/shade.sh
Add tools to package a shaded jar.
Shaded jar may be required by Flink SQL.
No.
No. 
Not needed.
> add tools to package a shaded jar

- .github/workflows/maven_build_main.yml
- .github/workflows/maven_build_pr.yml
- README.md
- README_CN.md
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/sink/OceanBaseSink.java
- tools/maven/build.sh
Add build script and workflow 
For testing.
No.
No.
Not needed.
> chore: add build script and workflow

- .github/workflows/maven_build_main.yml
- README.md
- README_CN.md
Add badges to README
To show project status better.
No.
No.
Not needed.
> chore: add badges to readme

- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/connection/OceanBaseConnectionPool.java
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/connection/OceanBaseConnectionProvider.java
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/sink/OceanBaseRowDataStatementExecutor.java
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/sink/OceanBaseSink.java
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/sink/OceanBaseWriter.java
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/table/OceanBaseConnectorOptions.java
Fix ide warnings.
Keep a clean code style.
No.
No.
Not needed.
> style: fix ide warnings

- README.md
- README_CN.md
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/sink/OceanBaseRowDataStatementExecutor.java
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/sink/OceanBaseWriterOptions.java
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/table/OceanBaseConnectorOptions.java
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/table/sink/OceanBaseDynamicTableSinkFactory.java
Make memstore check optional.
User should be able to skip the check.
No.
No.
Tested locally.
> feat: make memstore check optional

- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/connection/OceanBaseCompatibleMode.java
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/connection/OceanBaseConnectionPool.java
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/connection/OceanBaseConnectionProvider.java
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/sink/OceanBaseRowDataStatementExecutor.java
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/sink/OceanBaseSink.java
Use compatible mode as enum.
It's more clear to use enum.
No.
No.
Tested locally.
> refactor: use compatible mode enum

- README.md
- README_CN.md
- flink-connector-oceanbase/pom.xml
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/OceanBaseConnectorOptions.java
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/OceanBaseDynamicTableSinkFactory.java
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/connection/OceanBaseConnectionInfo.java
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/connection/OceanBaseConnectionOptions.java
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/connection/OceanBaseConnectionPool.java
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/connection/OceanBaseConnectionProvider.java
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/dialect/OceanBaseDialect.java
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/sink/statement/OceanBaseRowDataStatementExecutor.java
- flink-connector-oceanbase/src/test/java/com/oceanbase/connector/flink/sink/OceanBaseSinkTest.java
Add some startup options used to query table partition info.
Test locally.
New required options added, see the demo in README.
> feat: add options to query table entry

- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/connection/OceanBaseTableSchema.java
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/converter/OceanBaseRowConverter.java
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/sink/statement/OceanBaseRowDataStatementExecutor.java
- flink-connector-oceanbase/src/test/java/com/oceanbase/connector/flink/sink/OceanBaseSinkTest.java
Close #26.
Convert field data before set statement. 
Executed UT locally.
No breaking change.
> fix: convert field data before set statement

- README.md
- README_CN.md
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/OceanBaseConnectorOptions.java
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/OceanBaseDynamicTableSinkFactory.java
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/sink/OceanBaseWriterOptions.java
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/sink/statement/OceanBaseRowDataStatementExecutor.java
- flink-connector-oceanbase/src/test/java/com/oceanbase/connector/flink/sink/OceanBaseSinkTest.java
Add thread pool to execute sink sql parallelly, and the pool size equals to partition number.
> feat: add thread pool to execute statement in parallel

- .github/workflows/maven_build_main.yml
- .github/workflows/maven_build_pr.yml
Cache maven repos in build ci.
> build: cache maven repos in build ci

- flink-connector-obkv-hbase/pom.xml
- flink-connector-oceanbase/pom.xml
- pom.xml
Bump ob clients to latest version.
> chore: bump ob clients to latest version

- flink-connector-oceanbase/pom.xml
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/connection/OceanBaseConnectionPool.java
Bump ob-partition-calculator version to 1.8.0
> build(deps): bump ob-partition-calculator version to 1.8.0

- flink-connector-obkv-hbase/src/test/java/com/oceanbase/connector/flink/OBKVHBaseConnectorITCase.java
- flink-connector-oceanbase-base/src/test/java/com/oceanbase/connector/flink/OceanBaseTestBase.java
Update docker image tag to 4.2.1_bp2, which contains obconfigserver as a default service.
> build(test): update docker image tag to 4.2.1_bp2

- flink-connector-obkv-hbase/src/main/java/com/oceanbase/connector/flink/OBKVHBaseConnectorOptions.java
- flink-connector-obkv-hbase/src/main/java/com/oceanbase/connector/flink/connection/OBKVHBaseConnectionProvider.java
- flink-connector-obkv-hbase/src/main/java/com/oceanbase/connector/flink/sink/OBKVHBaseRecordFlusher.java
- flink-connector-oceanbase-base/src/main/java/com/oceanbase/connector/flink/table/HTableInfo.java
- flink-connector-oceanbase-base/src/main/java/com/oceanbase/connector/flink/utils/TableCache.java
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/sink/OceanBaseRecordFlusher.java
> chore: modify classes for serialization

- flink-connector-obkv-hbase/pom.xml
- flink-connector-oceanbase/pom.xml
- flink-sql-connector-obkv-hbase/pom.xml
- flink-sql-connector-oceanbase/pom.xml
- pom.xml
Modify the pom according to the same dependency "obkv-table-client" of the modules.
> chore: cleanup depdencies and set versions in dependencyManagement

- flink-connector-oceanbase-base/src/main/java/com/oceanbase/connector/flink/table/DataChangeRecord.java
- flink-connector-oceanbase-base/src/main/java/com/oceanbase/connector/flink/table/DataChangeRecordData.java
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/sink/OceanBaseRecordFlusher.java
Print records in jdbc flush error message.
> fix (log): print records in jdbc flush error message

- flink-connector-oceanbase-base/src/main/java/com/oceanbase/connector/flink/table/TableInfo.java
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/dialect/OceanBaseDialect.java
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/dialect/OceanBaseMySQLDialect.java
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/dialect/OceanBaseOracleDialect.java
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/sink/OceanBaseRecordFlusher.java
- flink-connector-oceanbase/src/test/java/com/oceanbase/connector/flink/OceanBaseConnectorITCase.java
- flink-connector-oceanbase/src/test/resources/sql/init.sql
Support user defined prepared statement placeholder and add a test case for gis types.
> feat: support user defined prepared statement placeholder

- README.md
- README_CN.md
Add Flink Connector JDBC to external project list.
> docs: add flink-connector-jdbc to readme

- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/connection/OceanBaseConnectionProvider.java
- flink-connector-oceanbase/src/test/java/com/oceanbase/connector/flink/connection/OceanBaseConnectionProviderTest.java
> Enhancement：Set default properties in jdbc url.

- flink-connector-oceanbase/src/test/java/com/oceanbase/connector/flink/OceanBaseMySQLConnectorITCase.java
- flink-connector-oceanbase/src/test/java/com/oceanbase/connector/flink/OceanBaseOracleConnectorITCase.java
UT error
Fix assertEquals param order
> [UT] Fix assertEquals param order

- flink-connector-oceanbase-base/src/main/java/com/oceanbase/connector/flink/table/HTableInfo.java
- flink-connector-oceanbase-base/src/main/java/com/oceanbase/connector/flink/table/Table.java
- flink-connector-oceanbase-base/src/main/java/com/oceanbase/connector/flink/table/TableInfo.java
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/sink/OceanBaseRecordFlusher.java
Add util method to check partition column names in jdbc connector.
> feat: check partition column names in jdbc connector

- flink-connector-obkv-hbase/pom.xml
- flink-connector-oceanbase/pom.xml
- pom.xml
> bump clients of OceanBase to latest version

- docs/sink/flink-connector-obkv-hbase.md
- docs/sink/flink-connector-obkv-hbase_cn.md
- flink-connector-obkv-hbase/src/main/java/com/oceanbase/connector/flink/OBKVHBaseConnectorOptions.java
- flink-connector-obkv-hbase/src/main/java/com/oceanbase/connector/flink/OBKVHBaseDynamicTableSinkFactory.java
> obkv-hbase: add default value to odp-port and update docs

- .github/workflows/push_pr.yml
- README.md
- README_CN.md
- docs/sink/flink-connector-oceanbase-directload.md
- docs/sink/flink-connector-oceanbase-directload_cn.md
> doc: Add doc for direct-load module.

- .github/workflows/push_pr.yml
- .github/workflows/test.yml
- flink-connector-oceanbase-e2e-tests/src/test/java/com/oceanbase/connector/flink/tests/OBDirectLoadE2eITCase.java
- flink-connector-oceanbase-e2e-tests/src/test/java/com/oceanbase/connector/flink/tests/OBKVHBaseE2eITCase.java
- flink-connector-oceanbase-e2e-tests/src/test/java/com/oceanbase/connector/flink/tests/OceanBaseE2eITCase.java
- flink-connector-oceanbase-e2e-tests/src/test/java/com/oceanbase/connector/flink/tests/utils/FlinkContainerTestEnvironment.java
> test: split e2e test by flink version

- flink-connector-oceanbase-base/src/test/java/com/oceanbase/connector/flink/OceanBaseMySQLTestBase.java
- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/table/OceanBaseRowDataSerializationSchema.java
- flink-connector-oceanbase/src/test/java/com/oceanbase/connector/flink/OceanBaseMySQLConnectorITCase.java
- flink-connector-oceanbase/src/test/resources/sql/mysql/array_type.sql
> Enhancement: Support Array data type of OceanBase.

- flink-connector-oceanbase/src/main/java/com/oceanbase/connector/flink/table/OceanBaseRowDataSerializationSchema.java
- flink-connector-oceanbase/src/test/java/com/oceanbase/connector/flink/OceanBaseMySQLConnectorITCase.java
- flink-connector-oceanbase/src/test/resources/sql/mysql/array_type.sql
Fix string array type write failure.
> BugFix: Fix string array type write failure.

- README.md
- README_CN.md
- docs/cli/README.md
- docs/cli/README_CN.md
- docs/cli/flink-cdc/flink-cdc-source.md
- docs/cli/flink-cdc/flink-cdc-source_cn.md
> docs: modify cli docs structure
